RegisterNetEvent(("%s:buyMask"):format(eDMask.Utils.PrefixEvent))
AddEventHandler(("%s:buyMask"):format(eDMask.Utils.PrefixEvent), function()
    eDMask.Utils.InSide("skinchanger:change", "mask_1", _Client.MainMenu.MaskIndex, -1)
    eDMask.Utils.InSide("skinchanger:change", "mask_2", _Client.MainMenu.MaskColorIndex)
    eDMask.Utils.InSide('skinchanger:getSkin', function(skin)
        eDMask.Utils.ServerSide('esx_skin:save', skin)
    end)
end)

RegisterNetEvent(("%s:notMoney"):format(eDMask.Utils.PrefixEvent))
AddEventHandler(("%s:notMoney"):format(eDMask.Utils.PrefixEvent), function()
    ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin)
        eDMask.Utils.InSide('skinchanger:loadSkin', skin)
    end)
end)

RegisterNetEvent(("%s:showNotification"):format(eDMask.Utils.PrefixEvent))
AddEventHandler(("%s:showNotification"):format(eDMask.Utils.PrefixEvent), function(msg)
    eDMask.Utils.ShowNotification(msg)
end)